# Generated by Django 4.2.6 on 2023-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='medida',
            field=models.CharField(choices=[('Pulgada', 'Pulgada'), ('Centimetro', 'Centimetro'), ('Milimetros', 'Milimetros'), ('Kilos', 'Kilos'), ('Miligramos', 'Miligramos'), ('Libras', 'Libras')], max_length=45, verbose_name='Medida'),
        ),
    ]
