# Generated by Django 4.2.5 on 2023-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de venta'),
        ),
    ]
