# Generated by Django 4.2.5 on 2023-10-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('ingreso_egreso', '0004_alter_detalle_venta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta_precio', to='producto.producto', verbose_name='Precio_venta'),
        ),
    ]
