# Generated by Django 4.1.7 on 2023-10-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('ingreso_egreso', '0005_alter_detalle_venta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=45, verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta_precio', to='producto.producto', verbose_name='Precio_venta'),
            preserve_default=False,
        ),
    ]
