# Generated by Django 4.1.7 on 2023-10-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('ingreso_egreso', '0006_alter_detalle_compra_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Producto'),
        ),
    ]
