# Generated by Django 4.2.6 on 2023-10-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0009_remove_stock_detalle_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='precio_venta',
        ),
    ]
