# Generated by Django 4.2.6 on 2023-11-01 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0010_remove_detalle_venta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=45, validators=[django.core.validators.MinValueValidator(limit_value=1, message='El precio de compra debe ser mayor que 0.')], verbose_name='Precio de compra'),
        ),
    ]
