# Generated by Django 4.2.5 on 2023-10-10 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+$', message='Este campo solo permite letras.')])),
                ('direccion', models.CharField(max_length=45, verbose_name='Dirección')),
                ('municipio', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+$', message='Este campo solo permite letras.')])),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')], verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+$', message='Este campo solo permite letras.')])),
                ('apellido', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+$', message='Este campo solo permite letras.')])),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')])),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', message='Este campo solo permite números.')])),
                ('direccion', models.CharField(max_length=15, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Por favor, ingresa una dirección de correo electrónico válida.')])),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Rol')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
