# Generated by Django 4.2.5 on 2023-10-10 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Cuenta_Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ]+$', message='Este campo solo permite letras.')])),
                ('fecha_inicio', models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Inicio')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=45, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d{1,2})?$', message='Ingresa un número válido con hasta 2 decimales.')], verbose_name='Precio')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=15, verbose_name='Estado')),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Nombre del Producto')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Pendientes',
            },
        ),
    ]
