# Generated by Django 4.2.6 on 2023-10-31 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_pendiente',
            name='valor_restar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=45, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d{1,2})?$', message='Ingresa un número válido con hasta 2 decimales.')], verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
