# Generated by Django 4.2.6 on 2023-10-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_cuenta_pendiente_valor_restar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_pendiente',
            name='valor_restar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=45, null=True, verbose_name='Valor a restar'),
        ),
    ]
